server:
  port: 8181

spring:
  # 环境 dev:开发环境|test:测试环境|prod:生产环境
  profiles:
    #激活的配置文件
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

# 文件系统
minio:
  url: http://47.93.236.174:9900/
  access-key: admin
  secret-key: admin123456
  bucket-name: young

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.young.springbootkafka.dao

#showSql
logging:
  level:
    com:
      young:
        springbootkafka :
          mapper: debug